stages:
- name: Build
  steps:
  - runScriptConfig:
      image: python:3.6-slim
      shellScript: |-
        apt update
        apt install -y make
        make ci
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: agent-timestamp-clustering:${CICD_EXECUTION_SEQUENCE}-${CICD_GIT_COMMIT}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
  when:
    branch:
      include:
      - master
notification: {}
